# Example 1

This example aims to show the usage of the decisiorama tool for solving MCDA problems. This example is based on the paper of Lahtinen 2007[addlink] 



In [1]:
# import libraries 
import sys
sys.path.insert(0, '..')

import numpy as np

import decisiorama
from decisiorama.pda.preference import Objective, Evaluator
from decisiorama.pda import utility, aggregate, ranker
import itertools

print(decisiorama)

<module 'decisiorama' from '..\\decisiorama\\__init__.py'>


## Definition of the solutions

Here we define the solutions. For each leaf objective, 

In [2]:
# Phosporous
p = np.array([[0.9, 1.1],
              [1.1, 1.3],
              [1.3, 1.7],
              [0.0, 0.0],
              [0.0, 0.0],
              [0.0, 0.0],
              [0.5, 0.6],
              [0.0, 0.0],
              [4.0, 4.8],])

# Nitrates
n2 = np.array([[0.09, 0.11],
               [0.09, 0.11],
               [0.14, 0.17],
               [0.00, 0.00],
               [0.00, 0.00],
               [0.00, 0.00],
               [0.00, 0.00],
               [0.00, 0.00],
               [0.40, 0.48],])

# Climate
climate = np.array([[0.0, 0.0],
                    [0.0, 0.0],
                    [0.5, 1.5],
                    [-1.5, -0.5],
                    [0.0, 0.0],
                    [0.5, 1.5],
                    [0.0, 0.0],
                    [0.0, 0.0],
                    [-2.5, -1.5],])

# Savings
savings = np.array([[1.8, 2.2],
                    [1.8, 2.2],
                    [1.8, 2.2],
                    [1.8, 2.2],
                    [0.9, 1.1],
                    [9.0, 11.0],
                    [32.0, 40.0],
                    [14.0, 18.0],
                    [3.5, 4.5],])

# Overall
overall = None

# Create of a dictionary with the solutions
sols = dict(p=p, n2=n2, climate=climate, savings=savings, overall=overall)

In [3]:
# Define the problem limits
costs = [1.0, 1.0, 2.0, 10.0, 8.0, 11.0, 43.0, 23.0, 20.0]
water = [0.03, 0.07, 0.04, 0.015, 0.10, 0.38, 0.15, 0.34, 0.46]
budget_limit = 45.0
n = 1000

In [4]:
obj_p = Objective(
        name = 'p',
        w = 0.25,
        alternatives = sols['p'], 
        obj_min = 0.0, 
        obj_max = 4.8, 
        n = n, 
        utility_func = utility.exponential, 
        utility_pars = [0.0, ], 
        aggregation_func = aggregate.additive, 
        aggregation_pars = None,
        maximise = False)

obj_n2 = Objective(
        name = 'n2',
        w = 0.25,
        alternatives = sols['n2'], 
        obj_min = 0.0, 
        obj_max = 0.48, 
        n = n, 
        utility_func = utility.exponential, 
        utility_pars = [0.0, ], 
        aggregation_func = aggregate.additive, 
        aggregation_pars = None,
        maximise = False)

obj_climate = Objective(
        name = 'climate',
        w = 0.25,
        alternatives = sols['climate'][:], 
        obj_min = -2.5, 
        obj_max = 1.5, 
        n = n, 
        utility_func = utility.exponential, 
        utility_pars = [0.0, ], 
        aggregation_func = aggregate.additive, 
        aggregation_pars = None,
        maximise = False)

obj_savings = Objective(
        name = 'savings',
        w = 0.25,
        alternatives = sols['savings'], 
        obj_min = 0.9, 
        obj_max = 40.0, 
        n = n, 
        utility_func = utility.exponential, 
        utility_pars = [0.0, ], 
        aggregation_func = aggregate.additive, 
        aggregation_pars = None,
        maximise = False)

obj_overall = Objective(
        name = 'overall',
        w = 0.25,
        alternatives = sols['climate'], 
        obj_min = 0.9, 
        obj_max = 40.0, 
        n = n, 
        utility_func = utility.exponential, 
        utility_pars = 0.0, 
        aggregation_func = aggregate.additive, 
        aggregation_pars = None,
        maximise = False)



In [5]:
x = [1,1,1,1,1,1,1,1,1]
print(obj_climate.get_value(x))

x = [0,0,0,0,0,0,0,0,0]
print(obj_climate.get_value(x))


[4.125 3.125]
[3.375 3.375]


In [6]:
print(sols['climate'])
print(sols['savings'])

[[ 0.   0. ]
 [ 0.   0. ]
 [ 0.5  1.5]
 [-1.5 -0.5]
 [ 0.   0. ]
 [ 0.5  1.5]
 [ 0.   0. ]
 [ 0.   0. ]
 [-2.5 -1.5]]
[[ 1.8  2.2]
 [ 1.8  2.2]
 [ 1.8  2.2]
 [ 1.8  2.2]
 [ 0.9  1.1]
 [ 9.  11. ]
 [32.  40. ]
 [14.  18. ]
 [ 3.5  4.5]]


In [7]:
sols

{'p': array([[0.9, 1.1],
        [1.1, 1.3],
        [1.3, 1.7],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0.5, 0.6],
        [0. , 0. ],
        [4. , 4.8]]), 'n2': array([[0.09, 0.11],
        [0.09, 0.11],
        [0.14, 0.17],
        [0.  , 0.  ],
        [0.  , 0.  ],
        [0.  , 0.  ],
        [0.  , 0.  ],
        [0.  , 0.  ],
        [0.4 , 0.48]]), 'climate': array([[ 0. ,  0. ],
        [ 0. ,  0. ],
        [ 0.5,  1.5],
        [-1.5, -0.5],
        [ 0. ,  0. ],
        [ 0.5,  1.5],
        [ 0. ,  0. ],
        [ 0. ,  0. ],
        [-2.5, -1.5]]), 'savings': array([[ 1.8,  2.2],
        [ 1.8,  2.2],
        [ 1.8,  2.2],
        [ 1.8,  2.2],
        [ 0.9,  1.1],
        [ 9. , 11. ],
        [32. , 40. ],
        [14. , 18. ],
        [ 3.5,  4.5]]), 'overall': None}

In [8]:
obj_overall.add_children(obj_p)
obj_overall.add_children(obj_n2)
obj_overall.add_children(obj_climate) 
obj_overall.add_children(obj_savings)


In [17]:
# prob = dict(p=p, n2=n2, climate=climate, savings=savings, 
#             overall=overall)

# test the problem solutions
x = [1,1,1,1,1,1,1,1,1]
obj_overall.get_value(x)


array([6.62595908, 6.10187553])

In [18]:
def filter_inps(inps):
    out = []
    def follow_up(pred, post):
        if post:
            if not pred:
                return False
        return True
        
    def mutual_exclusive(a, b):
        if a and b:
            return False
        return True

    for x in inps:        
    
        # follow up action
        if not follow_up(x[3], x[4]):
            continue
        
        # Mutually exclusive actions
        if not mutual_exclusive(x[3], x[5]):
            continue
        
        if not mutual_exclusive(x[6], x[7]):
            continue
        
        if not mutual_exclusive(x[6], x[8]):
            continue
     
        # Budget and water constraints
        budget = np.sum([a for i, a in enumerate(costs) if x[i]]) 
        if budget > budget_limit:
            continue
    
        water_target = 1.0 - np.prod([(1.0 - a) for i, a in enumerate(water) if x[i]])
        if water_target < 0.5:
            continue
        
        out.append(x)
    return out
# get all the results
inp_comb = list(itertools.product([0, 1], repeat=len(x)))

inps = np.array(filter_inps(inp_comb))
res = np.array(list(map(obj_overall.get_value, inps)))



In [24]:
ee = Evaluator(inps, res)
ee.add_function(ranker.mean, minimize=False)
# ee.add_function(ranker.mean, minimize=False)
ee.add_function(ranker.iqr, minimize=True)
# ee.get_pareto_solutions()

In [26]:
ee.get_pareto_solutions()

array([2], dtype=int64)

In [28]:
res

array([[7.2329497 , 7.05514706],
       [7.23366901, 7.00615409],
       [7.42695013, 7.32608696],
       [7.40470482, 7.1861413 ],
       [7.05532023, 6.77600171],
       [7.05603954, 6.72700874],
       [7.24932065, 7.0469416 ],
       [7.22707534, 6.90699595],
       [7.12302856, 6.92183504],
       [7.12374787, 6.87284207],
       [7.31702899, 7.19277494],
       [7.29478367, 7.05410806],
       [7.29478367, 7.05282928],
       [7.02915867, 6.75202472],
       [6.94611839, 6.59369672],
       [7.13939951, 6.91362958],
       [7.1171542 , 6.7749627 ],
       [7.1171542 , 6.77368393],
       [7.13344523, 6.93225171],
       [7.13416454, 6.88325874],
       [7.32744565, 7.2031916 ],
       [7.30520034, 7.06324595],
       [6.95653506, 6.60411338],
       [7.14981618, 6.92404625],
       [7.12757087, 6.78537937],
       [7.12757087, 6.7841006 ],
       [7.10728367, 6.90827472],
       [7.02352408, 6.79893968],
       [7.02424339, 6.74994672],
       [7.21752451, 7.06987958],
       [7.